import typing as t

from transformers import PreTrainedTokenizerFast

from .utils import (
    get_known_eos_or_eot,
    get_nltk_span_tokenizer,
    get_nltk_stopwords_set,
    get_punctuation_set,
    get_tokens_and_spans,
)


def much_segmentation(
    generation: str,
    llm_tokenizer: PreTrainedTokenizerFast,
    precomputed_tokens: t.Optional[t.List[int]] = None,
) -> t.List[t.List[int]]:
    """Segments an LLM generation into token chunks.

    The output is a list of token chunks. For example, if
    `llm_tokenizer.encode(generation)` returns six tokens, the result could be
    [[0, 1, 2], [3], [4, 5]]. In this case, three chunks are provided: one with
    three tokens, one with a single token, and one with two tokens.

    **Why provide a `precomputed_tokens` argument?**
    Modern subword tokenizers are not idempotent:
    `tokenizer(tokenizer.decode(tokens))` may differ from `tokens`. Consequently,
    the tokens generated by the LLM may not match the tokenization obtained
    post hoc from the decoded text. To ensure that the chunks returned by
    `much_segmentation` correspond to the tokens actually produced by the LLM,
    you should pass the LLM-generated tokens through `precomputed_tokens`.

    Parameters
    ----------
    generation : str
        The LLM generation as a string, possibly including the EOS token.
    llm_tokenizer : PreTrainedTokenizerFast
        The tokenizer associated with the LLM that produced the generation.
    precomputed_tokens : list[int] | None
        The tokenization of the generation, if already available.

    Returns
    -------
    list[list[int]]
        The list of chunks, where each chunk is represented as a list of token
        indices in the tokenized version of the generation (see example above).
    """

    # Init + loading
    nltk_tokenizer = get_nltk_span_tokenizer()
    segmentation_stopwords = get_nltk_stopwords_set()
    segmentation_punct_set = get_punctuation_set()

    # NLTK tokenization + stopwords detection
    word_indices = list(nltk_tokenizer.span_tokenize(generation))

    # Init containers for loop
    char_idx_of_claim_start = []
    previous_word_was_stopword = False
    next_word_is_stopword = False

    # Index of EOS
    eos_index = None
    for final_token in get_known_eos_or_eot(llm_tokenizer):
        if llm_tokenizer.decode(final_token) in generation:
            eos_index = generation.index(llm_tokenizer.decode(final_token))
            break
    if eos_index is None:
        eos_index = len(generation)

    # Iterating over NLTK words - the goal here is to fill char_idx_of_claim_start
    # We ommit "0" in char_idx_of_claim_start on purpose, to integrate with the LLM token part
    for word_start, word_stop in word_indices:
        # Did we reach EOS ?
        if word_stop >= eos_index:
            if eos_index < len(generation):
                char_idx_of_claim_start.append(eos_index)
            break

        # Is current word a stopword?
        current_word = generation[word_start:word_stop].lower().strip()
        word_is_stopword = (
            (current_word in segmentation_stopwords)
            or (current_word in segmentation_punct_set)
            or next_word_is_stopword
        )
        # We only add it if the previous word was not a stopword
        if word_is_stopword and (not previous_word_was_stopword) and (word_start != 0):
            char_idx_of_claim_start.append(word_start)

        # Next word is stopword - special case of "." char
        # Updating previous_word_was_stopword as well
        previous_word_was_stopword = word_is_stopword
        next_word_is_stopword = current_word[-1] == "."

    # Adding the last part to terminate chunks.
    if not char_idx_of_claim_start or char_idx_of_claim_start[-1] != len(generation):
        char_idx_of_claim_start.append(len(generation))

    # Now, we iterate on the LLM tokens and detect when we "cross" a char in char_idx_of_claim_start
    result = []
    current_chunk = []
    output_tokens, token_char_span = get_tokens_and_spans(
        generation, llm_tokenizer, precomputed_tokens
    )

    for idx_token in range(len(output_tokens)):

        # Finding the char idx of the end of the token
        char_index_of_token_end = token_char_span[idx_token][1]

        # Flushing or appending
        if (
            char_idx_of_claim_start != []
            and char_index_of_token_end > char_idx_of_claim_start[0]
            and current_chunk != []
        ):
            result.append(current_chunk)
            char_idx_of_claim_start = char_idx_of_claim_start[1:]
            current_chunk = [idx_token]
        else:
            current_chunk.append(idx_token)

    # Final flush
    if current_chunk != []:
        result.append(current_chunk)

    # Post-processing
    # If the last token is punctuation, include it in the final chunk.
    if len(result) >= 2:
        last_is_eos = len(result[-1]) == 1 and output_tokens[
            result[-1][0]
        ] in get_known_eos_or_eot(llm_tokenizer)
        if not last_is_eos:
            chunk_text = llm_tokenizer.decode(
                [output_tokens[i] for i in result[-1]]
            ).strip()
            if chunk_text in segmentation_punct_set:
                result[-2] = result[-2] + result[-1]
                result.pop()

    return result
