import string
import typing as t
from functools import lru_cache

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import TreebankWordTokenizer
from transformers import AutoTokenizer, PreTrainedTokenizerFast


@lru_cache
def get_tokenizer(model_name: str) -> PreTrainedTokenizerFast:
    """Gets the tokenizer."""
    return AutoTokenizer.from_pretrained(model_name)


def get_repr_string(
    generation: str,
    token_chunks: t.List[t.List[int]],
    tokenizer: PreTrainedTokenizerFast,
    precomputed_tokens: t.Optional[t.List[int]] = None,
    remove_latest: bool = False,
) -> str:
    """
    Build a string representation of the segmentation of a generated text.

    The function returns a formatted multi-line string where each line corresponds
    to one token chunk, showing its index and decoded text span. It can either
    use precomputed token IDs or re-tokenize the input text using the provided
    tokenizer.

    Parameters
    ----------
    generation : str
        The generated text, possibly including the EOS token.
    token_chunks : list[list[int]]
        A list of token index ranges, where each inner list defines the indices
        (inclusive) of a contiguous token span.
    tokenizer : PreTrainedTokenizerFast
        The tokenizer used to encode and decode the generation.
    precomputed_tokens : list[int] | None, optional
        Precomputed token IDs of the generation. If provided, the tokenizer is
        not used for encoding.
    remove_latest : bool, optional
        If True, the last token chunk is omitted from the representation. Useful
        for ignoring EOS/EOT token in the last chunk.

    Returns
    -------
    str
        A formatted string describing the token-level segmentation, where each
        line contains the chunk index and its decoded text span.
    """

    # Getting tokenized output
    if precomputed_tokens is not None:
        tokenized_output = precomputed_tokens
    else:
        tokenized_output = tokenizer.encode(generation, add_special_tokens=False)

    # Building result
    result = "<Segmentation>"
    for idx_chunk, chunk in enumerate(token_chunks):
        if remove_latest and idx_chunk == len(token_chunks) - 1:
            continue

        chunk_str = tokenizer.decode(tokenized_output[chunk[0] : chunk[-1] + 1])
        line_break = "\n" if result != "" else ""
        result += f"{line_break}#{idx_chunk:2} : {chunk_str}"

    return result


@lru_cache
def get_nltk_span_tokenizer() -> TreebankWordTokenizer:
    return TreebankWordTokenizer()


@lru_cache()
def get_nltk_stopwords_set():

    # Collect all stopwords NLTK knows
    all_langs = ["english", "spanish", "french", "german"]
    stopword_set = set()
    for lang in all_langs:
        try:
            stopword_set |= set(stopwords.words(lang))
        except (OSError, LookupError):
            nltk.download("stopwords")
            stopword_set |= set(stopwords.words(lang))

    # Extra stopwords - when needed

    return stopword_set


@lru_cache()
def get_punctuation_set():
    return set(string.punctuation) | {
        "،",
        "؛",
        "؟",
        "，",
        "。",
        "、",
        "？",
        "！",
        "：",
        "；",
        "（",
        "）",
        "《",
        "》",
        "“",
        "”",
        "¿",
        "¡",
        "«",
        "»",
        "…",
        "''",
        "``",
        "\n",
        "",
        "''",
        '""',
    }


def get_tokens_and_spans(
    generation: str,
    llm_tokenizer: PreTrainedTokenizerFast,
    precomputed_tokens: t.Optional[t.List[int]] = None,
) -> t.Tuple[t.List[int], t.List[tuple]]:
    """Returns tokens and their character spans for a given generation.

    If `precomputed_tokens` is not provided, the function tokenizes the
    generation directly and retrieves the character spans from the tokenizer's
    offset mapping. If `precomputed_tokens` is provided, spans are reconstructed
    from the decoded tokens. A `ValueError` is raised if the reconstructed
    length does not match the generation length, which may occur for
    non-idempotent tokenizers (e.g., BERT).

    Parameters
    ----------
    generation : str
        The text generated by the LLM.
    llm_tokenizer : PreTrainedTokenizerFast
        The tokenizer associated with the LLM.
    precomputed_tokens : list[int] | None
        Optional list of precomputed tokens for the generation.

    Returns
    -------
    tuple[list[int], list[tuple[int, int]]]
        A tuple containing the token IDs and their corresponding character spans.
    """
    if precomputed_tokens is None:
        tokenized_output = llm_tokenizer(
            generation, add_special_tokens=False, return_offsets_mapping=True
        )
        output_tokens = tokenized_output["input_ids"]
        token_char_span = tokenized_output["offset_mapping"]

        return output_tokens, token_char_span

    else:
        output_tokens = precomputed_tokens
        token_char_span = []
        previous_str_len = 0
        for token_idx in range(len(output_tokens)):
            current_str_len = len(llm_tokenizer.decode(output_tokens[: token_idx + 1]))
            token_char_span.append((previous_str_len, current_str_len))
            previous_str_len = current_str_len

        # Error if the size is incorrect
        if token_char_span[-1][1] != len(generation):
            raise ValueError(
                "Generation size mismatch detected. This may occur if your tokenizer does not satisfy "
                "`tokenizer.encode(tokenizer.decode(output_string)) == output_string` (as it is the case for BERT tokenizer) "
                "For such tokenizer, you should not provide pre-computed tokens."
            )

        return output_tokens, token_char_span


@lru_cache()
def get_known_eos_or_eot(llm_tokenizer: PreTrainedTokenizerFast) -> t.List[int]:
    """
    Retrieve known end-of-sequence (EOS) or end-of-turn (EOT) token IDs
    for the tokenizer.

    This function first includes the tokenizer's built-in EOS token ID, if available.
    It then checks whether the special token "<end_of_turn>" is recognized as a single token
    and, if so, includes its corresponding token ID as well.

    Parameters
    ----------
    tokenizer : PreTrainedTokenizerFast
        The tokenizer for which the tokens are needed.

    Returns
    -------
    list[int]
        A list of token IDs corresponding to known EOS or EOT markers.
    """

    result = []

    # First, add EOS token id
    if llm_tokenizer.eos_token_id is not None:
        result.append(llm_tokenizer.eos_token_id)

    # Then, check some known EOT schemes
    for tok in ["<end_of_turn>", "<|eot_id|>", "<EOT>", "<end>"]:
        eot_encoded = llm_tokenizer.encode(tok, add_special_tokens=False)
        if len(eot_encoded) == 1:
            result.append(eot_encoded[0])

    return list(dict.fromkeys(result))
